In [18]:
import pandas as pd
import datetime 
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sms
from scipy.signal import argrelextrema

df = pq.ParquetFile("win_1min.parquet").read().to_pandas()

In [19]:
df

,open,high,low,close,tick_volume,spread,real_volume
index,,,,,,,
2016-09-06 09:00:00,60500.0,60570.0,60500.0,60560.0,199,5,896
2016-09-06 09:01:00,60540.0,60640.0,60505.0,60540.0,544,5,1705
2016-09-06 09:02:00,60530.0,60550.0,60485.0,60490.0,277,5,758
2016-09-06 09:03:00,60485.0,60505.0,60330.0,60425.0,809,5,2444
2016-09-06 09:04:00,60425.0,60480.0,60420.0,60465.0,282,5,641
...,...,...,...,...,...,...,...
2021-09-21 17:51:00,110310.0,110365.0,110290.0,110355.0,670,0,4861
2021-09-21 17:52:00,110350.0,110365.0,110295.0,110305.0,621,0,5235
2021-09-21 17:53:00,110305.0,110325.0,110230.0,110280.0,747,0,4641
2021-09-21 17:54:00,110280.0,110395.0,110275.0,110370.0,332,0,2991
2021-09-21 18:01:00,110240.0,110240.0,110240.0,110240.0,2,0,7315

In [ ]:
minimo_local_range = 5

df_ = df.copy

# script para localizar mÃ­nimos locais no grafico

df+["i"] = np.arange(len(df_))

local_min_idx = argrelextrema(df_.low.values, np.less, order=minimo_local_range, mode="wrap")[0]
local_max_idx = argrelextrema(df_.high.values, np.greater, order=minimo_local_range, mode="wrap")[0]
local_min_idx = np.array(local_min_idx)
local+local_max_idx = np.array(local_max_idx)


local_min=[]
local_max=[]

for loc in local_min_idx:
    local_min.append(df_.low[loc])

for loc in local_max_idx:
    local_min.append(df_.high[loc])
    
local_min = np.array(local_min)
local_max = np.array(local_max)

#minuto 8:19